/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import BancoDados.ConexaoMySQL;
import java.text.ParseException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import BancoDados.ResultadoBusca;
import BancoDados.ResultadoBuscaProdutos;
import Exceptions.NaoAchouException;
import negocio.Fachada;
import negocio.FachadaProduto;

/**
 *
 * @author Ollawo
 */
public class BuscarProduto extends javax.swing.JFrame {
    private String TelaFuncionario = "deletar";
    int check;
    /**
     * Creates new form BuscarCliente
     */
    public BuscarProduto() {
        initComponents();
    }
    
       public void setTelaFuncionario(String TelaFuncionario){
           this.TelaFuncionario=TelaFuncionario;
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jFormattedTextFieldBusca = new javax.swing.JFormattedTextField();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonID = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Produto");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");

        buttonGroup1.add(jRadioButtonNome);
        jRadioButtonNome.setSelected(true);
        jRadioButtonNome.setText("Nome do Produto");

        buttonGroup1.add(jRadioButtonID);
        jRadioButtonID.setText("Código do Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNome)
                            .addComponent(jRadioButtonID))
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBuscar)
                            .addComponent(jFormattedTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jRadioButtonNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonID)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

    	if (jRadioButtonID.isSelected()){
    		check =2;
    	}else if (jRadioButtonNome.isSelected()) {
    		check = 1;
    	}
    	
    	ResultadoBuscaProdutos result = new ResultadoBuscaProdutos();
        try {
			result = FachadaProduto.getInstance().pesquisar(jFormattedTextFieldBusca.getText(),check);
		} catch (NaoAchouException e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
        
        if (!(result.getNome().equals(null)) && this.TelaFuncionario.equals("alterar")) {
        	AlterarProduto frame = new AlterarProduto();
        	frame.setVisible(true);  
            frame.setResultado(result);
            frame.carregar();
        }else if (!(result.getNome().equals(null)) && this.TelaFuncionario.equals("deletar")){
        	DeletarProduto frame = new DeletarProduto();
        	frame.setVisible(true);  
            frame.setResultado(result);
            frame.carregar();
        }
        /*
        try {
            Connection con = ConexaoMySQL.getInstance().getConnection();
            String cmd = "Select * from produtos";
            ResultSet res= con.createStatement().executeQuery(cmd);
            if(jRadioButtonNome.isSelected()){
                while (res.next()){
                    String nome = res.getString("nome");
                    if(jFormattedTextFieldBusca.getText().equals(nome)){
                        if (TelaFuncionario.equals("alterar")){
                        AlterarProduto frame = new AlterarProduto();
                        frame.setBusca(nome);
                        frame.setCheck(1);
                        frame.setVisible(true);  
                        frame.carregar();
                        }else if (TelaFuncionario.equals("deletar")){
                        DeletarProduto frame = new DeletarProduto();
                        frame.setBusca(nome);
                        frame.setCheck(1);
                        frame.setVisible(true);
                        frame.carregar();
                        } 
                    }
                }
                //Não encontrou o produto pelo nome
            }else if (jRadioButtonID.isSelected()){
                while (res.next()){
                    String id = res.getString("idproduto");
                    if(jFormattedTextFieldBusca.getText().equals(id)){
                        if (TelaFuncionario.equals("alterar")){
                        DeletarProduto frame = new DeletarProduto();
                        frame.setBusca(id);
                        frame.setCheck(2);
                        frame.setVisible(true);
                        frame.carregar();
                        }else if (TelaFuncionario.equals("deletar")){
                        DeletarProduto frame = new DeletarProduto();
                        frame.setBusca(id);
                        frame.setCheck(2);
                        frame.setVisible(true);
                        frame.carregar();
                        }
                    }
                }
                //Não encontrou o produto pelo código
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }*/
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFormattedTextField jFormattedTextFieldBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonID;
    private javax.swing.JRadioButton jRadioButtonNome;
    // End of variables declaration//GEN-END:variables
}
